// <auto-generated />
namespace MusicCollection2017.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UnknownChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnknownChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191057132_UnknownChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
